FROM debian:jessie
 
ENV DEBIAN_FRONTEND noninteractive
 
RUN apt-get update -qqy
RUN apt-get install -qqy php5-cli php5-json curl

RUN echo 'date.timezone = Europe/Amsterdam' >> /etc/php5/cli/php.ini

RUN curl -sS https://getcomposer.org/installer | php

VOLUME ["/srv"]
WORKDIR /srv
RUN useradd composer
USER composer

ENTRYPOINT ["/composer.phar"]